### ISSUE TITLE
Ability to integrate a delay when list is driven by an AJAX request

### ISSUE THREAD

**Issue by aforloney** [Fischer-L/autoComplt#7]
When an autocomplete list is driven based off of data sent back from an AJAX request, the ```hintsFetcher``` function would be called for each character typed. An example where this could be problematic would be a text-box that populates the autocomplete list of users based on the value typed into the ```autoCompleteElement``` textbox.

```javascript
var inp = document.getElementById("autoCompleteElement");
 autoComplt.enable(inp, {
     hintsFetcher: function (val, openList) {
           var params = {};
            // setup the user parameter for AJAX call
            params.user = val;
            $.ajax({
                type: 'GET',
                url: ...,
                dataType: "jsonp",
                data: params,
                success: function (jsonData) {
                    openList(jsonData.data);
                },
            });
        }
 ```

An AJAX request will be generated for each character typed into the box. This is undesirable if I were to be typing an user with an extremely long name where N requests is generated for N characters.

One approach to mitigate this sort of problem would be to incorporate a property that can be set on ```autoComplt``` to delay hint fetching after a certain time once the user had stopped typing.

This would resolve the problem for multiple requests being sent over to the server as it would only be generated once when the user has stopped typing.

**Comment by aforloney** [comment]
Another feature that would be nice to have for the same sort of example usage would be to have a property on the ```autoComplt``` object to accept an optional ```function``` that would be invoked after the end-user had selected an item in the dropdown list.

**Comment by Fischer-L** [comment]
Thanks for feedback.

The 1st issue of multiple requests:
It is able to config the delay time already. The default is 250 ms. Increasing the delay would ease the multiple request issue but sacrifice the responsiveness. A trade-off.
I also add one fix to check the current input value is equal to the value passed to the hintFetcher before calling the hintFetcher. If not, no call happens so as to reduce the redundant calls.

The 2nd issue about the select event listener:
Just add this.

p.s:
I found that Gmail puts the emails from Github into the junk email box. The result is that I miss lots of Github notifications and respond kind of late ...
